#!/usr/bin/env python3
import click
from weapon import simple_dice


@click.command()
def cli():
    """Run the program."""
    for _ in range(10000):
        pass  # Kasta...

    # Skriv ut resultat

    click.echo("It's alive!")


if __name__ == "__main__":
    cli()
